//! Do not edit this file manually, it is generate by `prisma repo generator`

import _ from 'lodash';
import { PrismaClient, Prisma, RosesCms } from '@prisma/client';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AnyRecord = Record<string, any>;

export type BaseOption<Include, Select> = {
  include?: Include;
  select?: Select;
};

export type Find<Select, Include, Cursor, Order, Distinct> = BaseOption<Include, Select> & {
  cursor?: Cursor;
  take?: number;
  skip?: number;
  orderBy?: Prisma.Enumerable<Order>;
  distinct?: Distinct;
};

export type CountArgs<Select, Cursor, Order, Distinct> = Omit<
  Find<Select, never, Cursor, Order, Distinct>,
  'include'
>;

export type Aggregate<Cursor, Order, Distinct> = Omit<
  CountArgs<never, Cursor, Order, Distinct>,
  'select' | 'distinct'
>;

export const prisma = new PrismaClient({
  log: ['query', 'info', 'warn', 'error'],
});

export const models = _.omit(prisma, [
  '$on',
  '$connect',
  '$disconnect',
  '$use',
  '$executeRaw',
  '$executeRawUnsafe',
  '$queryRaw',
  '$queryRawUnsafe',
  '$transaction',
]);

export const MODELS_NAME = {
  ROSES_CMS: 'rosesCms',
} as const;

// eslint-disable-next-line @typescript-eslint/ban-types
export type ModelStructure = {
  rosesCms: RosesCms;
};

export type ModelName = keyof ModelStructure;

export type ModelScalarFields<T extends keyof ModelStructure> = Prisma.Enumerable<keyof ModelStructure[T]>;

export type ModelDelegate = Prisma.RejectOnNotFound | Prisma.RejectPerOperation | undefined;

export type ModelTypes = {
  rosesCms: {
    Where: Prisma.RosesCmsWhereInput;
    Select: Prisma.RosesCmsSelect;
    Include: unknown;
    Create: Prisma.RosesCmsCreateInput | Prisma.RosesCmsUncheckedCreateInput;
    Update: Prisma.RosesCmsUpdateInput | Prisma.RosesCmsUncheckedUpdateInput;
    Cursor: Prisma.RosesCmsWhereUniqueInput;
    Order: Prisma.RosesCmsOrderByWithRelationInput;
    Delegate: Prisma.RosesCmsDelegate<ModelDelegate>;
  };
};
